In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
ad=pd.read_csv("/content/Advertising.csv")

In [12]:
ad.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [13]:
ad.isnull().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [14]:
ad.drop(columns=["Unnamed: 0"],axis=1,inplace=True)

In [15]:
ad.shape

(200, 4)

In [16]:
ad.dtypes

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [17]:
# displaying the datatypes
display(ad.dtypes)

# converting 'Weight' from float to int
ad['TV'] = ad['TV'].astype(int)
ad["Radio"] = ad["Radio"].astype(int)
ad["Newspaper"] = ad["Newspaper"].astype(int)
ad["Sales"] = ad["Sales"].astype(int)
# displaying the datatypes
display(ad.dtypes)

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

TV           int64
Radio        int64
Newspaper    int64
Sales        int64
dtype: object

In [18]:
ad.head()

    TV  Radio  Newspaper  Sales
0  230     37         69     22
1   44     39         45     10
2   17     45         69      9
3  151     41         58     18
4  180     10         58     12

In [19]:
X=ad.drop(columns=["Sales"])
y=ad.Sales

In [20]:
X

      TV  Radio  Newspaper
0    230     37         69
1     44     39         45
2     17     45         69
3    151     41         58
4    180     10         58
..   ...    ...        ...
195   38      3         13
196   94      4          8
197  177      9          6
198  283     42         66
199  232      8          8

[200 rows x 3 columns]

In [21]:
def gradient_descent(X,y):
  pass

In [22]:
# Example 1: Convert specific column use to_numpy()
X = ad['TV'].to_numpy()
X = ad['Radio'].to_numpy()
x = ad['Newspaper'].to_numpy()
print(X)

[37 39 45 41 10 48 32 19  2  2  5 24 35  7 32 47 36 39 20 23 27  5 15 16
 12  3 29 16 27 16 28 17  1 20  1  4 43 49 26 37 22 33 27  8 25 22  9 41
 15 11  3  9 41 46 28 49 28 19 49 29  2 42 15 29 42  9 24 14 27 43 30 14
 33  5 24 43  1 28 29  7 26  4 20 44 43 18 27 40 25 47  4  1 33 36 14 31
  3 21 42 41  4 36 10 17 34 46 11  0  0 26  8 38 15 20 46 35 14  0 36 16
 26 21  2 34 32 11 38  0 49 12 39  2 27 33 38 47 39 28 25 43 17 35 33  5
 14  1  7 49 40 25 13  8 23 39 21 11 43  1 36 18 18 35 18 36 14  3 37  5
 23 10 11 20 20  7  3 48 30  7  2 10  2  5  5 43 21 45  2 28 13 12 41 10
  4 42 35  3  4  9 42  8]

In [23]:
y = ad['Sales'].to_numpy()
print(y)

[22 10  9 18 12  7 11 13  4 10  8 17  9  9 19 22 12 24 11 14 18 12  5 15
  9 12 15 15 18 10 21 11  9 17  9 12 25 14 10 21 16 17 20 12  8 14 10 23
 14  9 11 10 22 21 20 23  5 13 23 18  8 24 15 14 18  9  9 13 18 22 18 12
  8 11 17  8  6 14  5 11 11 12 11 13 21 15 12 16 12 16 11  7 19 22 11 16
 11 15 25 17 11 23 14 14 20 19  7  8  5 19 13 21 14 15 14 12 12  9 15  6
 15  7 11 15 19 10  6  8 24  9  1 12  5 19 10 11  9 20  9 20 10 19 20 10
 11 10 13 25 10 10 16 11 16 19 15  3 15 10  7 12 14 13 14 18 11 11  8 12
 17 15  8 14  7 11 11 27 20 11 11 12 10 12  8 26 17 22 10 17 15  6 10  9
  5 19 17  7  9 12 25 13]

### commenly we can use this code for gradient_descent

In [24]:
def gradient_descent(X,y):
  m_curr=b_curr=0
  iterations=10
  learning_rate=0.001
  n=len(X)
  for i in range(iterations):
    yp=m_curr*X+b_curr
    cost=(1/n)*sum([val**2 for val in i(y-yp)])
    md=-(2/n)*sum(X*(y-yp))
    bd=-(2/n)*sum(y-yp)
    m_curr= m_curr-learning_rate*md
    b_curr=b_curr-learning_rate*bd
    print("n{},b{},cost{},iteration{}".format(m_curr,b_curr,cost,i))
    pass
    X=np.array[37,39,45,41,10,48,42,35,3]
    y=np.array[22,10,19,17,7,9,12,25,13]
    gradient_descent(X,y)